CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;

CREATE TABLE AUTHORS (
    AUTHOR_ID INT NOT NULL,
    AUTHOR_NAME VARCHAR(215),
    PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE BOOKS (
    BOOK_ID INT NOT NULL,
    TITLE VARCHAR(130),
    AUTHOR_ID INT NOT NULL,
    PRICE DOUBLE,
    PUBLICATION_DATE DATE,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT NOT NULL,
    CUSTOMER_NAME VARCHAR(215),
    EMAIL VARCHAR(215),
    ADDRESS TEXT,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE ORDER_DETAILS (
    ORDERDETAILID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    PRIMARY KEY (ORDERDETAILID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
